### PR TITLE
playercntl: Allow further locking of ships

### PR DESCRIPTION
**Pull request by dsyalex**
* Lock HpCM* (Cloaks, Cloak Disruptors) as well as cargo
* Allow for an extra lock level that restricts selling anything.

http://discoverygc.com/forums/showthread.php?tid=146200

### CODE REVIEW

**Comment by zibbizor** [comment]
This is good, perhaps we could also lock the HpSpecialEquipment slots as these are bound to receive use.

**Comment by dsyalex** [comment]
There's another ini problem with that, talking to the dev chat.

**Comment by dsyalex** [comment]
Update: I've been having trouble convincing people to look into the issue I found. I'll go ahead and update this later anyway, though it may not be 100% effective for locking HpSpecialEquipment in discovery for now

**Comment by dsyalex** [comment]
Turns out it got fixed and I wasn't notified (or if I was, I didn't receive it) - DGCRepository commit c65513db7241f5a7a3a0fbdc8c2aa5e2fbb782ed

**Pull request merged**
