### PR TITLE
Cope with commas in event tracker data

### PR DESCRIPTION
**Pull request by dsydalziel**

### CODE REVIEW

**Comment by dsyalex** [comment]
Why was this closed?

**Comment by dsydalziel** [comment]
Oh hey. It worked (I think) but it was a bit of a hasty hack. The ideal solution was to encode the data, which I started working on around that time. Unfortunately that work is gone now as my hard drive went bang last year (and with it some commits I hadn't pushed).

**Comment by dsyalex** [comment]
Do you remember what the topics of those unpushed commits were?

**Comment by dsydalziel** [comment]
Pretty sure that was the only one of any use. Any others were most likely grotesque experimental abominations that should never have been unleashed upon the world anyway!

**Pull request closed without merging**
